# Generated by Django 4.1.2 on 2022-10-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.IntegerField(choices=[(0, 'Admin'), (1, 'Cliente')], default=0, verbose_name='Tipo'),
        ),
    ]
